### ISSUE TITLE
I should be able to search for my own tweets, even if my account is private

### ISSUE THREAD

**Issue by AllanMukundi** [xdevplatform/search-tweets-python#164]
**Describe the bug**

I want to be able to search for my own tweets in the search bar, even if my account is private.

**To Reproduce**
Steps (and code snippet) to reproduce the behavior:

1. Change account audience to protected
2. Search `@user "[some word you have tweeted before]"`
3.

<img width="600" alt="Screenshot 2023-04-28 at 12 16 22 PM" src="https://user-images.githubusercontent.com/19519445/235234059-9d1f9215-8fa4-490c-87ce-58780680e48f.png">

**Expected behavior**

To see my tweets appear in the search results.

**Environment**
 - OS: [e.g. macOS Ventura 13.3.1, Twitter web client on Firefox 112.0 (all browsers though)]

**Comment by jimmoffitt** [comment]
This code has nothing to do with the search bar.
